apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-api
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: demo-api
  template:
    metadata:
      labels:
        app: demo-api
    spec:
      tolerations:
        - key: "gpu"
          value: "true"
          effect: "NoExecute"
      containers:
        - name: demo-api
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          envFrom:
            - configMapRef:
                name: demo-api-config
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 2
            periodSeconds: 5
